# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr: none

variables:
  gitCommitHash: '$(Build.SourceVersion)'
  imageName: 'hauki-admin-ui'
  azureSubscription: HKI-kanslia-standalone
  appName: hauki-admin-ui
  containerRegistry: registry.hub.docker.com

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
- script: |
    yarn cache clean
  displayName: 'yarn cache clean'

- script: |
    yarn install
  displayName: 'Yarn install'

- script: |
    yarn lint
  displayName: 'Yarn lint'

- script: |
    CI=true yarn test
  displayName: 'Yarn run tests'

- script: |
    CI=true yarn test-cypress-with-new-test-api
  displayName: 'Yarn run cypress (e2e) tests'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/cypress/videos'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  condition: failed()

- task: Docker@2
  displayName: Build and push Hauki admin ui image to docker hub
  inputs:
    containerRegistry: Docker hub upload-hauki-admin-ui
    repository: 'helsinki/$(imageName)'
    command: buildAndPush
    tags: |
      latest
      $(gitCommitHash)
    Dockerfile: Dockerfile-old

- task: oc-cmd@2
  displayName: Deploy image to openshift, add OC tag to latest image
  inputs:
    openshiftService: Azure OpenShift-hauki-admin-ui
    cmd: 'tag docker.io/helsinki/hauki-admin-ui:$(gitCommitHash) hauki-admin-ui:latest'

- task: Bash@3
  displayName: Wait for deploy to finish
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here

      sleep 50

- script: |
   CI=true yarn test-cypress-with-new-test-env
  displayName: 'Yarn run cypress (e2e) tests against test environment'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/cypress/videos'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  condition: failed()
