# File: hauki-admin-ui/master-to-test.pipeline.yml

variables:
  gitCommitHash: '$(Build.SourceVersion)'

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

# By default, use self-hosted agents
pool: Default

# Opting out of pull request validation
pr: none

resources:
  repositories:
  # Azure DevOps repository
  - repository: hauki-pipelines
    type: git
    # project/repository
    name: hauki/hauki-pipelines

extends:
  template: hauki-admin-ui-test.pipeline.yml@hauki-pipelines
