# Continuous integration (CI) triggers cause a pipeline to run whenever you push 
# an update to the specified branches or you push specified tags.
trigger: none

# By default, use self-hosted agents
pool: Production

# Opting out of pull request validation
pr: none

resources:
  repositories:
  # Azure DevOps repository
  - repository: hauki-pipelines
    type: git
    # project/repository
    name: hauki/hauki-pipelines

extends:
  template: azure-pipelines-build-hauki-admin-ui-stageprod.yml@hauki-pipelines
