# File: hauki-admin-ui/azure-pipelines.yml

# Continuous integration (CI) triggers cause a pipeline to run whenever you push 
# an update to the specified branches or you push specified tags.
trigger:
  branches:
    include:
    - master
    - feature/*
  paths:
    exclude:
    - README.md

# By default, use self-hosted agents
pool: Default

resources:
  repositories:
  # Azure DevOps repository
  - repository: hauki-pipelines
    type: git
    # project/repository
    name: hauki/hauki-pipelines

extends:
  template: azure-pipelines-hauki-admin-ui.yml@hauki-pipelines
